version: '3'

services:
  db:
    build: ./services/database-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
    healthcheck:
        test: "/usr/bin/mysql --user=users_service --password=123 --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
  
    environment:
        DB_NAME: "PRODUCTMANAGER"
        DB_PASSWORD: "123" 
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        DB_HOST: "db"
        DB_USER: "users_service"
        DB_PORT: "3318"

  product-management-ms:
    container_name: product-management-ms
    build:
      context: ./services/product-management
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - MESSAGE_BUS=amqp://rabbitmq

  